[package]
name = "text-engine"
version = "0.1.0"
authors = ["Maya <mabodominguez@hmc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
